export const RepData = [['Chittenden-2', 'Angela Arsenault', ['Williston'], 'Democrat'],
['Chittenden-19', 'Sarah "Sarita" Austin', ['Colchester'], 'Democrat'],
['Lamoille-2', 'Richard Bailey', ['Belvidere', 'Hyde Park', 'Johnson', 'Wolcott'], 'Republican'],
['Windsor-1', 'John L. Bartholomew', ['Hartland', 'West Windsor', 'Windsor'], 'Democrat'],
['Franklin-1', 'Ashley Bartley', ['Fairfax', 'Georgia'], 'Republican/Democrat'],
['Chittenden-21', 'Daisy Berbeco', ['Winooski'], 'Democrat'],
['Addison-3', 'Matthew Birong', ['Addison', 'Ferrisburgh', 'New Haven', 'Panton', 'Vergennes', 'Waltham'], 'Democrat'],
['Chittenden-20', 'Doug Bishop', ['Colchester'], 'Democrat'],
['Chittenden-24', 'Alyssa Black', ['Essex'], 'Democrat'],
['Chittenden-13', 'Tiffany Bluemle', ['Burlington'], 'Democrat'],
['Windham-3', 'Michelle Bos-Lun', ['Brookline', 'Rockingham', 'Westminster'], 'Democrat'],
['Rutland-2', 'David "Dave" Bosch', ['Clarendon', 'Rutland', 'Wallingford', 'West Rutland'], 'Republican'],
['Washington-3', 'Michael Boutin', ['Barre'], 'Republican'],
['Lamoille-3', 'Lucy Boyden', ['Cambridge', 'Waterville'], 'Democrat'],
['Chittenden-2', 'Erin Brady', ['Williston'], 'Democrat'],
['Franklin-1', 'Carolyn Branagan', ['Fairfax', 'Georgia'], 'Republican'],
['Republican', 'Rutland-3', ['Rutland'], ''],
['Chittenden-1', 'Jana Brown', ['Richmond'], 'Democrat'],
['Rutland-2', 'Thomas Burditt', ['Clarendon', 'Rutland', 'Wallingford', 'West Rutland'], 'Republican'],
['Windham-8', 'Mollie S. Burke', ['Brattleboro'], 'Democrat'],
['Chittenden-8', 'Bridget Burkhardt', ['South Burlington', 'Williston'], 'Democrat'],
['Windsor-1', 'Elizabeth Burrows', ['Hartland', 'West Windsor', 'Windsor'], 'Democrat'],
['Caledonia-Washington', 'Gregory "Greg" Burtt', ['Cabot', 'Danville', 'Peacham'], 'Republican'],
['Caledonia-Essex', 'R. Scott Campbell', ['Concord', 'Kirby', 'St. Johnsbury'], 'Democrat'],
['Rutland-10', 'William Canfield', ['Benson', 'Fair Haven', 'West Haven'], 'Republican'],
['Windham-6', 'Emily Carris-Duncan', ['Halifax', 'Whitingham', 'Wilmington'], 'Democrat'],
['Washington-4', 'Conor Casey', ['Montpelier'], 'Democrat'],
['Addison-Rutland', 'James "Jim" Casey', ['Hubbardton', 'Orwell', 'Shoreham', 'Sudbury', 'Whiting'], 'Republican'],
['Washington-5', 'Ela Chapin', ['East Montpelier', 'Middlesex'], 'Democrat'],
['Windsor-Windham', 'Thomas "Tom" Charlton', ['Athens', 'Chester', 'Grafton', 'Windham'], 'Republican'],
['Windsor-6', 'Kevin "Coach" Christie', ['Hartford'], 'Democrat'],
['Chittenden-15', 'Brian Cina', ['Burlington'], 'Progressive/Democrat'],
['Windsor-2', 'VL Coffin IV', ['Baltimore', 'Cavendish', 'Weathersfield'], 'Republican'],
['Windsor-6', 'Esme Cole', ['Hartford'], 'Democrat'],
['Addison-2', 'Peter Conlon', ['Cornwall', 'Goshen', 'Leicester', 'Ripton', 'Salisbury'], 'Democrat'],
['Bennington-1', 'Jonathan Cooper', ['Pownal', 'Readsboro', 'Searsburg', 'Stamford', 'Woodford'], 'Democrat'],
['Bennington-2', 'Timothy R. Corcoran II', ['Bennington'], 'Democrat'],
['Addison-4', 'Mari Cordes', ['Bristol', 'Lincoln', 'Monkton', 'Starksboro'], 'Democrat'],
['Chittenden-19', 'Wendy Critchlow', ['Colchester'], 'Democrat'],
['Franklin-7', 'Allen "Penny" Demar', ['Enosburgh', 'Montgomery'], 'Republican'],
['Franklin-2', 'Eileen Dickinson', ['St. Albans'], 'Republican'],
['Orange-3', 'Joshua Dobrovich', ['Chelsea', 'Williamstown'], 'Republican'],
['Chittenden-23', 'Leonora Dodge', ['Essex'], 'Democrat'],
['Chittenden-22', 'Karen Dolan', ['Essex'], 'Democrat'],
['Caledonia-Essex', 'Deborah "Debbie" Dolgin', ['Concord', 'Kirby', 'St. Johnsbury'], 'Republican'],
['Washington-1', 'Anne B. Donahue', ['Berlin', 'Northfield'], 'Independent'],
['Chittenden-17', 'Abbey Duke', ['Burlington'], 'Democrat'],
['Bennington-3', 'David Durfee', ['Glastenbury', 'Shaftsbury', 'Sunderland'], 'Democrat'],
['Windham-1', 'Zon Eastes', ['Guilford', 'Vernon'], 'Democrat'],
['Windsor-3', 'Alice M. Emmons', ['Springfield'], 'Democrat'],
['Caledonia-3', 'Martha Feltus', ['Lyndon', 'Newark', 'Sheffield', 'Sutton', 'Wheelock'], 'Republican'],
['Washington-Orange', 'Gina Galfetti', ['Barre', 'Williamstown'], 'Republican'],
['Chittenden-23', 'Golrang "Rey" Garofano', ['Essex'], 'Democrat'],
['Windham-3', 'Leslie Goldman', ['Brookline', 'Rockingham', 'Westminster'], 'Democrat'],
['Windham-9', 'Ian Goodnow', ['Brattleboro'], 'Democrat'],
['Washington-1', 'Kenneth Goslant', ['Berlin', 'Northfield'], 'Republican'],
['Chittenden-3', 'Edye Graning', ['Jericho', 'Underhill'], 'Democrat'],
['Bennington-2', 'William "Will" Greer', ['Bennington'], 'Democrat'],
['Franklin-6', 'James Gregoire', ['Bakersfield', 'Fairfield', 'Fletcher'], 'Republican'],
['Franklin-5', 'Lisa Hango', ['Berkshire', 'Franklin', 'Highgate', 'Richford'], 'Republican'],
['Orleans-4', 'Leanne Harple', ['Albany', 'Craftsbury', 'Glover', 'Greensboro'], 'Democrat'],
['Rutland-11', 'Jim Harrison', ['Chittenden', 'Killington', 'Mendon', 'Pittsfield'], 'Republican'],
['Rutland-3', 'Zachary Harvey', ['Castleton'], 'Republican'],
['Chittenden-15', 'Troy Headrick', ['Burlington'], 'Independent'],
['Orleans-Lamoille', 'Mark Higley', ['Coventry', 'Eden', 'Irasburg', 'Jay', 'Lowell', 'Newport', 'Troy', 'Westfield'], 'Republican'],
['Windsor-Orange-2', 'Rebecca Holcombe', ['Norwich', 'Sharon', 'Strafford', 'Thetford'], 'Democrat'],
['Orange-Washington-Addison', 'Philip Jay Hooper', ['Braintree', 'Brookfield', 'Granville', 'Randolph', 'Roxbury'], 'Democrat'],
['Chittenden-18', 'Robert Hooper', ['Burlington'], 'Democrat'],
['Chittenden-22', 'Lori Houghton', ['Essex'], 'Democrat'],
['Rutland-6', 'Mary E. Howard', [], 'Democrat'],
['Rutland-4', 'Christopher Howland', ['Rutland'], 'Republican'],
['Bennington-4', 'Robert Hunter', ['Arlington', 'Manchester', 'Sandgate', 'Sunderland'], 'Democrat'],
['Bennington-4', 'Kathleen James', ['Arlington', 'Manchester', 'Sandgate', 'Sunderland'], 'Democrat'],
['Essex-Caledonia', 'John Kascenska', ['Bloomfield', 'Brunswick', 'Burke', 'East Haven', 'Ferdinand', 'Granby', 'Guildhall', 'Lunenburg', 'Maidstone', 'Victory'], 'Republican'],
['Rutland-7', 'Chris Keyser', [], 'Republican'],
['Windsor-5', 'Charles Kimbell', ['Plymouth', 'Reading', 'Woodstock'], 'Democrat'],
['Chittenden-13', 'Bram Kleppner', ['Burlington'], 'Democrat'],
['Windham-7', 'Emilie Kornheiser', ['Brattleboro'], 'Democrat'],
['Chittenden-9', 'Emilie Krasnow', ['South Burlington'], 'Democrat'],
['Chittenden-16', 'Jill Krowinski', ['Burlington'], 'Democrat'],
['Essex-Orleans', 'Larry Labor', ['Averill', 'Avery\'s', 'Brighton', 'Canaan', 'Charleston', 'Holland', 'Lemington', 'Lewis', 'Morgan', 'Norton', 'Warner\'s', 'Warren\'s'], 'Republican'],
['Chittenden-6', 'Kate Lalley', ['Shelburne', 'South Burlington'], 'Democrat'],
['Chittenden-12', 'Martin LaLonde', ['South Burlington'], 'Democrat'],
['Lamoille-Washington', 'Saudia LaMont', ['Elmore', 'Morristown', 'Stowe', 'Woodbury', 'Worcester'], 'Democrat'],
['Franklin-5', 'Wayne Laroche', ['Berkshire', 'Franklin', 'Highgate', 'Richford'], 'Republican'],
['Lamoille-1', 'Jed Lipsky', ['Stowe'], 'Independent'],
['Chittenden-16', 'Kate Logan', ['Burlington'], 'Progressive/Democrat'],
['Windham-5', 'Emily Long', ['Marlboro', 'Newfane', 'Townshend'], 'Democrat'],
['Franklin-3', 'Joseph "Joe" Luneau', ['St. Albans'], 'Republican'],
['Rutland-5', 'Eric Maguire', ['Rutland'], 'Republican'],
['Rutland-8', 'Alicia Malay', ['Pittsford', 'Proctor'], 'Republican/Democrat'],
['Orleans-Lamoille', 'Michael Marcotte', ['Coventry', 'Eden', 'Irasburg', 'Jay', 'Lowell', 'Newport', 'Troy', 'Westfield'], 'Republican'],
['Windsor-Orange-2', 'James Masland', ['Norwich', 'Sharon', 'Strafford', 'Thetford'], 'Democrat'],
['Washington-4', 'Kate McCann', ['Montpelier'], 'Democrat'],
['Rutland-1', 'Patricia McCoy', ['Ira', 'Poultney', 'Wells'], 'Republican'],
['Washington-Orange', 'Francis McFaun', ['Barre', 'Williamstown'], 'Republican'],
['Addison-5', 'Jubilee McGill', ['Bridport', 'Middlebury', 'New Haven', 'Weybridge'], 'Democrat'],
['Chittenden-Franklin', 'Anthony "Tony" Micklus', ['Georgia', 'Milton'], 'Republican'],
['Washington-6', 'Marc Mihaly', ['Calais', 'Marshfield', 'Plainfield'], 'Democrat'],
['Chittenden-11', 'Brian Minier', ['South Burlington'], 'Democrat'],
['Grand Isle-Chittenden', 'Leland Morgan', ['Alburgh', 'Grand Isle', 'Milton', 'North Hero', 'South Hero'], 'Republican'],
['Grand Isle-Chittenden', 'Michael Morgan', ['Alburgh', 'Grand Isle', 'Milton', 'North Hero', 'South Hero'], 'Republican'],
['Windsor-3', 'Kristi Morris', ['Springfield'], 'Democrat'],
['Bennington-5', 'Mary A. Morrissey', ['Bennington', 'Pownal'], 'Republican'],
['Windham-Windsor-Bennington', 'Christopher Morrow', ['Andover', 'Londonderry', 'Weston', 'Winhall'], 'Democrat'],
['Windham-4', 'Michael Mrowicki', ['Dummerston', 'Putney'], 'Democrat'],
['Orleans-1', 'Richard Nelson', ['Derby'], 'Republican'],
['Rutland-9', 'Todd Nielsen', ['Brandon'], 'Republican'],
['Bennington-5', 'Michael Nigro', ['Bennington', 'Pownal'], 'Democrat'],
['Addison-3', 'Rob North', ['Addison', 'Ferrisburgh', 'New Haven', 'Panton', 'Vergennes', 'Waltham'], 'Republican'],
['Lamoille-2', 'Daniel Noyes', ['Belvidere', 'Hyde Park', 'Johnson', 'Wolcott'], 'Democrat'],
['Chittenden-10', 'Kate Nugent', ['South Burlington'], 'Democrat'],
['Windsor-Orange-1', 'John O\'Brien', ['Royalton', 'Tunbridge'], 'Democrat'],
['Chittenden-18', 'Carol Ode', ['Burlington'], 'Democrat'],
['Franklin-4', 'Thomas Oliver', ['Sheldon', 'Swanton'], 'Republican/Democrat'],
['Addison-4', 'Herb Olson', ['Bristol', 'Lincoln', 'Monkton', 'Starksboro'], 'Democrat'],
['Orleans-2', 'Woodman Page', ['Newport'], 'Republican'],
['Orange-Caledonia', 'Joseph Parsons', ['Groton', 'Newbury', 'Topsham'], 'Republican'],
['Chittenden-20', 'Gayle Pezzo', ['Colchester'], 'Democrat'],
['Bennington-Rutland', 'Sandra "Sandy" Pinsonault', ['Danby', 'Dorset', 'Landgrove', 'Mount Tabor', 'Peru'], 'Republican'],
['Chittenden-4', 'Phil Pouech', ['Hinesburg'], 'Democrat'],
['Caledonia-1', 'Debra Powers', ['Barnet', 'Ryegate', 'Waterford'], 'Republican'],
['Orange-2', 'Monique Priestley', ['Bradford', 'Fairlee', 'West Fairlee'], 'Democrat'],
['Rutland-Bennington', 'Christopher "Chris" Pritchard', ['Middletown Springs', 'Pawlet', 'Rupert', 'Tinmouth', 'Wells'], 'Republican'],
['Caledonia-3', 'Beth Quimby', ['Lyndon', 'Newark', 'Sheffield', 'Sutton', 'Wheelock'], 'Republican'],
['Chittenden-14', 'Barbara Rachelson', ['Burlington'], 'Democrat'],
['Orange-Washington-Addison', 'Larry Satcowitz', ['Braintree', 'Brookfield', 'Granville', 'Randolph', 'Roxbury'], 'Democrat'],
['Addison-1', 'Robin Scheu', ['Middlebury'], 'Democrat'],
['Addison-1', 'Amy Sheldon', ['Middlebury'], 'Democrat'],
['Windham-2', 'Laura Sibilia', ['Dover', 'Jamaica', 'Somerset', 'Stratton', 'Wardsboro'], 'Independent'],
['Caledonia-2', 'Michael "Mike" Southworth', ['Hardwick', 'Stannard', 'Walden'], 'Republican'],
['Chittenden-3', 'Trevor Squirrell', ['Jericho', 'Underhill'], 'Democrat'],
['Chittenden-25', 'Brenda Steady', ['Milton', 'Westford'], 'Republican'],
['Washington-Chittenden', 'Thomas Stevens', ['Bolton', 'Buels', 'Huntington', 'Waterbury'], 'Democrat'],
['Chittenden-14', 'Mary-Katherine Stone', ['Burlington'], 'Democrat'],
['Windsor-4', 'Heather Surprenant', ['Barnard', 'Bridgewater', 'Hartford', 'Pomfret'], 'Democrat'],
['Chittenden-7', 'Shawn Sweeney', ['Shelburne', 'St. George'], 'Democrat'],
['Orange-1', 'Michael "Mike" Tagliavia', ['Corinth', 'Orange', 'Vershire', 'Washington'], 'Republican'],
['Chittenden-Franklin', 'Chris Taylor', ['Georgia', 'Milton'], 'Republican'],
['Chittenden-21', 'Chloe Tomlinson', ['Winooski'], 'Progressive/Democrat'],
['Franklin-8', 'Casey Toof', ['St. Albans'], 'Republican'],
['Washington-2', 'Dara Torre', ['Duxbury', 'Fayston', 'Moretown', 'Waitsfield', 'Warren'], 'Democrat'],
['Franklin-4', 'Matt Walker', ['Sheldon', 'Swanton'], 'Republican'],
['Washington-3', 'Edward "Teddy" Waszazak', ['Barre'], 'Democrat'],
['Chittenden-5', 'Chea Waters Evans', ['Charlotte', 'Hinesburg'], 'Democrat'],
['Orleans-3', 'Kenneth "Ken" Wells', ['Barton', 'Brownington', 'Westmore'], 'Republican'],
['Washington-2', 'Candice White', ['Duxbury', 'Fayston', 'Moretown', 'Waitsfield', 'Warren'], 'Democrat'],
['Windsor-Addison', 'Kirk White', ['Bethel', 'Hancock', 'Rochester', 'Stockbridge'], 'Democrat'],
['Rutland-Windsor', 'Kevin Winter', ['Ludlow', 'Mount Holly', 'Shrewsbury'], 'Republican'],
['Washington-Chittenden', 'Theresa Wood', ['Bolton', 'Buels', 'Huntington', 'Waterbury'], 'Democrat'],
['Lamoille-Washington', 'David Yacovone', ['Elmore', 'Morristown', 'Stowe', 'Woodbury', 'Worcester'], 'Democrat']];