export const RepData = [
  ['Addison-1', 'Bridget Burkhardt', ['Middlebury'], 'Democrat'],
  ['Addison-1', 'Amy Sheldon', ['Middlebury'], 'Democrat'],
  ['Addison-2', 'Peter Conlon', ['Cornwall', 'Goshen', 'Leicester', 'Ripton', 'Salisbury'], 'Democrat'],
  ['Addison-3', 'Matthew Birong', ['Addison', 'Ferrisburgh', 'New Haven', 'Panton', 'Vergennes', 'Waltham'], 'Democrat'],
  ['Addison-3', 'Robert "Rob" North', ['Addison', 'Ferrisburgh', 'New Haven', 'Panton', 'Vergennes', 'Waltham'], 'Republican'],
  ['Addison-4', 'Mari Cordes', ['Bristol', 'Lincoln', 'Monkton', 'Starksboro'], 'Democrat'],
  ['Addison-4', 'Herb Olson', ['Bristol', 'Lincoln', 'Monkton', 'Starksboro'], 'Democrat'],
  ['Addison-5', 'Jubilee McGill', ['Bridport', 'Middlebury', 'New Haven', 'Weybridge'], 'Democrat'],
  ['Addison-Rutland', 'James "Jim" Casey', ['Orwell', 'Shoreham', 'Whiting', 'Hubbardton', 'Sudbury'], 'Republican'],
  ['Bennington-1', 'Jonathan Cooper', ['Pownal', 'Readsboro', 'Searsburg', 'Stamford', 'Woodford'], 'Democrat'],
  ['Bennington-2', 'William "Will" Greer', ['Bennington'], 'Democrat'],
  ['Bennington-2', 'Mike Rice', ['Bennington'], 'Democrat'],
  ['Bennington-3', 'David Durfee', ['Glastenbury', 'Shaftsbury', 'Sunderland'], 'Democrat'],
  ['Bennington-4', 'Kathleen James', ['Arlington', 'Manchester', 'Sandgate', 'Sunderland'], 'Democrat'],
  ['Bennington-4', 'Robert Hunter', ['Arlington', 'Manchester', 'Sandgate', 'Sunderland'], 'Democrat'],
  ['Bennington-5', 'Mary A. Morrissey', ['Bennington', 'Pownal'], 'Republican'],
  ['Bennington-5', 'Michael Nigro', ['Bennington', 'Pownal'], 'Democrat'],
  ['Bennington-Rutland', 'Sandra "Sandy" Pinsonault', ['Dorset', 'Landgrove', 'Peru', 'Danby', 'Mount Tabor'], 'Republican'],
  ['Caledonia-1', 'Debra Powers', ['Barnet', 'Ryegate', 'Waterford'], 'Republican'],
  ['Caledonia-2', 'Michael "Mike" Tagliavia', ['Hardwick', 'Stannard', 'Walden'], 'Republican'],
  ['Caledonia-3', 'Martha Feltus', ['Lyndon', 'Newark', 'Sheffield', 'Sutton', 'Wheelock'], 'Republican'],
  ['Caledonia-3', 'Beth Quimby', ['Lyndon', 'Newark', 'Sheffield', 'Sutton', 'Wheelock'], 'Republican'],
  ['Caledonia-Essex', 'Deborah "Debbie" Dolgin', ['Kirby', 'St. Johnsbury', 'Concord'], 'Republican'],
  ['Caledonia-Essex', 'R. Scott Campbell', ['Kirby', 'St. Johnsbury', 'Concord'], 'Democrat'],
  ['Caledonia-Washington', 'Gregory "Greg" Burtt', ['Danville', 'Peacham', 'Cabot'], 'Republican'],
  ['Chittenden-1', 'Jana Brown', ['Richmond'], 'Democrat'],
  ['Chittenden-2', 'Angela Arsenault', ['Williston'], 'Democrat'],
  ['Chittenden-2', 'Erin Brady', ['Williston'], 'Democrat'],
  ['Chittenden-3', 'Trevor Squirrell', ['Jericho', 'Underhill'], 'Democrat'],
  ['Chittenden-3', 'Esme Cole', ['Jericho', 'Underhill'], 'Democrat'],
  ['Chittenden-4', 'Phil Pouech', ['Hinesburg'], 'Democrat'],
  ['Chittenden-5', 'Chea Waters Evans', ['Charlotte', 'Hinesburg'], 'Democrat'],
  ['Chittenden-6', 'Kate Lalley', ['Shelburne'], 'Democrat'],
  ['Chittenden-7', 'Shawn Sweeney', ['Shelburne', 'St. George'], 'Democrat'],
  ['Chittenden-8', 'Bridget Burkhardt', ['South Burlington', 'Williston'], 'Democrat'],
  ['Chittenden-9', 'Emilie Krasnow', ['South Burlington'], 'Democrat'],
  ['Chittenden-10', 'Kate Nugent', ['South Burlington'], 'Democrat'],
  ['Chittenden-11', 'Brian Minier', ['South Burlington'], 'Democrat'],
  ['Chittenden-12', 'Martin LaLonde', ['South Burlington'], 'Democrat'],
  ['Chittenden-13', 'Tiffany Bluemle', ['Burlington'], 'Democrat'],
  ['Chittenden-13', 'Bram Kleppner', ['Burlington'], 'Democrat'],
  ['Chittenden-14', 'Barbara Rachelson', ['Burlington'], 'Democrat'],
  ['Chittenden-14', 'Mary-Katherine Stone', ['Burlington'], 'Democrat/Progressive'],
  ['Chittenden-15', 'Brian Cina', ['Burlington'], 'Progressive/Democrat'],
  ['Chittenden-15', 'Troy Headrick', ['Burlington'], 'Progressive/Democrat'],
  ['Chittenden-16', 'Kate Logan', ['Burlington'], 'Progressive/Democrat'],
  ['Chittenden-16', 'Jill Krowinski', ['Burlington'], 'Democrat'],
  ['Chittenden-17', 'Abbey Duke', ['Burlington'], 'Democrat'],
  ['Chittenden-18', 'Carol Ode', ['Burlington'], 'Democrat'],
  ['Chittenden-18', 'Robert Hooper', ['Burlington'], 'Democrat'],
  ['Chittenden-19', 'Wendy Critchlow', ['Colchester'], 'Democrat'],
  ['Chittenden-19', 'Sarah "Sarita" Austin', ['Colchester'], 'Democrat'],
  ['Chittenden-20', 'Doug Bishop', ['Colchester'], 'Democrat'],
  ['Chittenden-20', 'Gayle Pezzo', ['Colchester'], 'Democrat'],
  ['Chittenden-21', 'Daisy Berbeco', ['Winooski'], 'Democrat'],
  ['Chittenden-21', 'Chloe Tomlinson', ['Winooski'], 'Progressive/Democrat'],
  ['Chittenden-22', 'Lori Houghton', ['Essex'], 'Democrat'],
  ['Chittenden-22', 'Karen Dolan', ['Essex'], 'Democrat'],
  ['Chittenden-23', 'Golrang "Rey" Garofano', ['Essex'], 'Democrat'],
  ['Chittenden-23', 'Leonora Dodge', ['Essex'], 'Democrat'],
  ['Chittenden-24', 'Alyssa Black', ['Essex'], 'Democrat'],
  ['Chittenden-25', 'Brenda Steady', ['Milton', 'Westford'], 'Republican'],
  ['Chittenden-Franklin', 'Chris Taylor', ['Milton', 'Georgia'], 'Republican'],
  ['Chittenden-Franklin', 'Anthony "Tony" Micklus', ['Milton', 'Georgia'], 'Republican'],
  ['Essex-Caledonia', 'John Kascenska', ['Burke', 'Bloomfield', 'Brunswick', 'East Haven', 'Ferdinand', 'Granby', 'Guildhall', 'Lunenburg', 'Maidstone', 'Victory'], 'Republican'],
  ['Essex-Orleans', 'Larry Labor', ['Averill', 'Avery\'s', 'Brighton', 'Canaan', 'Lemington', 'Lewis', 'Norton', 'Warner\'s', 'Warren\'s', 'Charleston', 'Holland', 'Morgan'], 'Republican'],
  ['Franklin-1', 'Carolyn Branagan', ['Fairfax', 'Georgia'], 'Republican'],
  ['Franklin-1', 'Ashley Bartley', ['Fairfax', 'Georgia'], 'Republican/Democrat'],
  ['Franklin-2', 'Eileen Dickinson', ['St. Albans'], 'Republican'],
  ['Franklin-3', 'Joseph "Joe" Luneau', ['St. Albans'], 'Republican'],
  ['Franklin-4', 'Matt Walker', ['Sheldon', 'Swanton'], 'Republican'],
  ['Franklin-4', 'Thomas Oliver', ['Sheldon', 'Swanton'], 'Republican/Democrat'],
  ['Franklin-5', 'Lisa Hango', ['Berkshire', 'Franklin', 'Highgate', 'Richford'], 'Republican'],
  ['Franklin-5', 'Wayne Laroche', ['Berkshire', 'Franklin', 'Highgate', 'Richford'], 'Republican'],
  ['Franklin-6', 'James Gregoire', ['Bakersfield', 'Fairfield', 'Fletcher'], 'Republican'],
  ['Franklin-7', 'Allen "Penny" Demar', ['Enosburgh', 'Montgomery'], 'Republican'],
  ['Franklin-8', 'Casey Toof', ['St. Albans'], 'Republican'],
  ['Grand Isle-Chittenden', 'Michael Morgan', ['Alburgh', 'Grand Isle', 'Milton', 'North Hero', 'South Hero'], 'Republican'],
  ['Grand Isle-Chittenden', 'Leland Morgan', ['Alburgh', 'Grand Isle', 'Milton', 'North Hero', 'South Hero'], 'Republican'],
  ['Lamoille-1', 'Jed Lipsky', ['Stowe'], 'Independent'],
  ['Lamoille-2', 'Richard Bailey', ['Belvidere', 'Hyde Park', 'Johnson', 'Wolcott'], 'Republican'],
  ['Lamoille-2', 'Saudia LaMont', ['Belvidere', 'Hyde Park', 'Johnson', 'Wolcott'], 'Democrat'],
  ['Lamoille-3', 'Lucy Boyden', ['Cambridge', 'Waterville'], 'Democrat'],
  ['Lamoille-Washington', 'Avram Patt', ['Elmore', 'Morristown', 'Stowe', 'Woodbury', 'Worcester'], 'Democrat'],
  ['Lamoille-Washington', 'David Yacovone', ['Elmore', 'Morristown', 'Stowe', 'Woodbury', 'Worcester'], 'Democrat'],
  ['Orange-1', 'Carl Demrow', ['Corinth', 'Orange', 'Vershire', 'Washington'], 'Democrat'],
  ['Orange-2', 'Monique Priestley', ['Bradford', 'Fairlee', 'West Fairlee'], 'Democrat'],
  ['Orange-3', 'Joshua Dobrovich', ['Chelsea', 'Williamstown'], 'Republican'],
  ['Orange-Caledonia', 'Joseph Parsons', ['Groton', 'Newbury', 'Topsham'], 'Republican'],
  ['Orange-Washington-Addison', 'Larry Satcowitz', ['Granville', 'Braintree', 'Brookfield', 'Randolph', 'Roxbury'], 'Democrat'],
  ['Orange-Washington-Addison', 'Robin Scheu', ['Granville', 'Braintree', 'Brookfield', 'Randolph', 'Roxbury'], 'Democrat'],
  ['Orleans-1', 'Richard Nelson', ['Derby'], 'Republican'],
  ['Orleans-2', 'Woodman Page', ['Newport'], 'Republican'],
  ['Orleans-3', 'Kenneth "Ken" Wells', ['Barton', 'Brownington', 'Westmore'], 'Republican'],
  ['Orleans-4', 'Leanne Harple', ['Albany', 'Craftsbury', 'Glover', 'Greensboro'], 'Democrat'],
  ['Orleans-Lamoille', 'Mark Higley', ['Eden', 'Coventry', 'Irasburg', 'Jay', 'Lowell', 'Newport', 'Troy', 'Westfield'], 'Republican'],
  ['Orleans-Lamoille', 'Michael Marcotte', ['Eden', 'Coventry', 'Irasburg', 'Jay', 'Lowell', 'Newport', 'Troy', 'Westfield'], 'Republican'],
  ['Rutland-1', 'Patricia McCoy', ['Ira', 'Poultney', 'Wells'], 'Republican'],
  ['Rutland-2', 'Thomas Burditt', ['Clarendon', 'Rutland', 'Wallingford', 'West Rutland'], 'Republican'],
  ['Rutland-2', 'David "Dave" Bosch', ['Clarendon', 'Rutland', 'Wallingford', 'West Rutland'], 'Republican'], 
  ['Rutland-3', 'Chris Brown', ['Castleton'], 'Republican'], 
  ['Rutland-4', 'Christopher Howland', ['Rutland'], 'Republican'], 
  ['Rutland-5', 'Eric Maguire', ['Rutland'], 'Republican'], 
  ['Rutland-6', 'Mary E. Howard', ['Rutland'], 'Democrat'], 
  ['Rutland-7', 'Chris Keyser', ['Rutland'], 'Republican'], 
  ['Rutland-8', 'Alicia Malay', ['Pittsford', 'Proctor'], 'Republican/Democrat'], 
  ['Rutland-9', 'Todd Nielsen', ['Brandon'], 'Republican'], 
  ['Rutland-10', 'William Canfield', ['Benson', 'Fair Haven', 'West Haven'], 'Republican'], 
  ['Rutland-11', 'James Harrison', ['Chittenden', 'Killington', 'Mendon', 'Pittsfield'], 'Republican'], 
  ['Rutland-Bennington', 'Christopher "Chris" Pritchard', ['Rupert', 'Middletown Springs', 'Pawlet', 'Tinmouth', 'Wells'], 'Republican'], 
  ['Rutland-Windsor', 'Kevin Winter', ['Mount Holly', 'Shrewsbury', 'Ludlow'], 'Republican'], 
  ['Washington-1', 'Anne B. Donahue', ['Berlin', 'Northfield'], 'Independent'], 
  ['Washington-1', 'Kenneth Goslant', ['Berlin', 'Northfield'], 'Republican'], 
  ['Washington-2', 'Dara Torre', ['Duxbury', 'Fayston', 'Moretown', 'Waitsfield', 'Warren'], 'Democrat'], 
  ['Washington-2', 'Candice White', ['Duxbury', 'Fayston', 'Moretown', 'Waitsfield', 'Warren'], 'Democrat'], 
  ['Washington-3', 'Peter Anthony', ['Barre'], 'Democrat'], 
  ['Washington-3', 'Edward "Teddy" Waszazak', ['Barre'], 'Democrat'], 
  ['Washington-4', 'Conor Casey', ['Montpelier'], 'Democrat'], 
  ['Washington-4', 'Kate McCann', ['Montpelier'], 'Democrat'], 
  ['Washington-5', 'Ela Chapin', ['East Montpelier', 'Middlesex'], 'Democrat'], 
  ['Washington-6', 'Marc Mihaly', ['Calais', 'Marshfield', 'Plainfield'], 'Democrat'], 
  ['Washington-Chittenden', 'Thomas Stevens', ['Bolton', 'Buels', 'Huntington', 'Waterbury'], 'Democrat'], 
  ['Washington-Chittenden', 'Theresa Wood', ['Bolton', 'Buels', 'Huntington', 'Waterbury'], 'Democrat'], 
  ['Washington-Orange', 'Francis McFaun', ['Williamstown', 'Barre'], 'Republican'], 
  ['Washington-Orange', 'James Masland', ['Williamstown', 'Barre'], 'Democrat'], 
  ['Windham-1', 'Zon Eastes', ['Guilford', 'Vernon'], 'Democrat'], 
  ['Windham-2', 'Laura Sibilia', ['Dover', 'Jamaica', 'Somerset', 'Stratton', 'Wardsboro'], 'Independent'], 
  ['Windham-3', 'Leslie Goldman', ['Brookline', 'Rockingham', 'Westminster'], 'Democrat'], 
  ['Windham-3', 'Michelle Bos-Lun', ['Brookline', 'Rockingham', 'Westminster'], 'Democrat'], 
  ['Windham-4', 'Michael Mrowicki', ['Dummerston', 'Putney'], 'Democrat'], 
  ['Windham-5', 'Emily Long', ['Marlboro', 'Newfane', 'Townshend'], 'Democrat'], 
  ['Windham-6', 'Emily Carris-Duncan', ['Halifax', 'Whitingham', 'Wilmington'], 'Democrat'], 
  ['Windham-7', 'Emilie Kornheiser', ['Brattleboro'], 'Democrat'], 
  ['Windham-8', 'Mary-Katherine Stone', ['Brattleboro'], 'Democrat/Progressive'], 
  ['Windham-9', 'Ian Goodnow', ['Brattleboro'], 'Democrat'], 
  ['Windham-Windsor-Bennington', 'Christopher Morrow', ['Winhall', 'Londonderry', 'Andover', 'Weston'], 'Democrat'], 
  ['Windsor-1', 'Elizabeth Burrows', ['Hartland', 'West Windsor', 'Windsor'], 'Democrat/Progressive'], 
  ['Windsor-1', 'John L. Bartholomew', ['Hartland', 'West Windsor', 'Windsor'], 'Democrat'], 
  ['Windsor-2', 'VL Coffin IV', ['Baltimore', 'Cavendish', 'Weathersfield'], 'Republican'], 
  ['Windsor-3', 'Kristi Morris', ['Springfield'], 'Democrat'], 
  ['Windsor-3', 'Alice M. Emmons', ['Springfield'], 'Democrat'], 
  ['Windsor-4', 'Heather Surprenant', ['Barnard', 'Bridgewater', 'Hartford', 'Pomfret'], 'Democrat'], 
  ['Windsor-5', 'Charles Kimbell', ['Plymouth', 'Reading', 'Woodstock'], 'Democrat'], 
  ['Windsor-6', 'Esme Cole', ['Hartford'], 'Democrat'], 
  ['Windsor-6', 'Kevin "Coach" Christie', ['Hartford'], 'Democrat'], 
  ['Windsor-Addison', 'Kirk White', ['Hancock', 'Bethel', 'Rochester', 'Stockbridge'], 'Democrat'], 
  ['Windsor-Orange-1', 'John OBrien', ['Tunbridge', 'Royalton'], 'Democrat'], 
  ['Windsor-Orange-2', 'Rebecca Holcombe', ['Strafford', 'Thetford', 'Norwich', 'Sharon'], 'Democrat'], 
  ['Windsor-Orange-2', 'James Masland', ['Strafford', 'Thetford', 'Norwich', 'Sharon'], 'Democrat'], 
  ['Windsor-Windham', 'Heather Chase', ['Athens', 'Grafton', 'Windham', 'Chester'], 'Democrat'] ];