export const SenatorData = [
    ['Chittenden-Central District', 'Philip Baruth', 'Democrat/Progressive'],
    ['Caledonia District', 'Scott Beck', 'Republican'],
    ['Bennington District', 'Seth Bongartz', 'Democrat'],
    ['Grand Isle District', 'Patrick "Pat" Brennan', 'Republican'],
    ['Franklin District', 'Randy Brock', 'Republican'],
    ['Chittenden-Southeast District', 'Thomas Chittenden', 'Democrat'],
    ['Windsor District', 'Alison Clarkson', 'Democrat'],
    ['Rutland District', 'Brian Collamore', 'Republican'],
    ['Washington District', 'Ann Cummings', 'Democrat'],
    ['Orleans District', 'Samuel "Sam" Douglass', 'Republican'],
    ['Chittenden-Central District', 'Martine Larocque Gulick', 'Democrat'],
    ['Addison District', 'Ruth Hardy', 'Democrat'],
    ['Windham District', 'Wendy Harrison', 'Democrat'],
    ['Orange District', 'Larry Hart', 'Republican'],
    ['Windham District', 'Nader Hashim', 'Democrat'],
    ['Addison District', 'Steven Heffernan', 'Republican'],
    ['Essex District', 'Russ Ingalls', 'Republican'],
    ['Chittenden-Southeast District', 'Virginia "Ginny" Lyons', 'Democrat'],
    ['Windsor District', 'Joseph "Joe" Major', 'Democrat'],
    ['Chittenden-North District', 'Christopher "Chris" Mattos', 'Republican'],
    ['Franklin District', 'Robert Norris', 'Republican'],
    ['Washington District', 'Andrew Perchlik', 'Democrat/Progressive'],
    ['Bennington District', 'Robert "Rob" Plunkett', 'Democrat'],
    ['Chittenden-Southeast District', 'Kesha Ram Hinsdale', 'Democrat'],
    ['Chittenden-Central District', 'Tanya Vyhovsky', 'Progressive/Democrat'],
    ['Washington District', 'Anne Watson', 'Democrat/Progressive'],
    ['Rutland District', 'David Weeks', 'Republican'],
    ['Lamoille District', 'Richard Westman', 'Republican'],
    ['Windsor District', 'Rebecca "Becca" White', 'Democrat'],
    ['Rutland District', 'Terry Williams', 'Republican']

  ];
  