export const townToDistrict = [
    ['Addison', 'Addison District'],
    ['Albany', 'Orleans District'],
    ['Alburgh', 'Franklin District'],
    ['Andover', 'Windsor District'],
    ['Arlington', 'Bennington District'],
    ['Athens', 'Windham District'],
    ['Averill', 'Essex District'],
    ['Avery\'s Gore', 'Essex District'],
    ['Bakersfield', 'Franklin District'],
    ['Baltimore', 'Windsor District'],
    ['Barnard', 'Windsor District'],
    ['Barnet', 'Caledonia District'],
    ['Barre City', 'Washington District'],
    ['Barre Town', 'Washington District'],
    ['Barton', 'Orleans District'],
    ['Belvidere', 'Lamoille District'],
    ['Bennington', 'Bennington District'],
    ['Benson', 'Rutland District'],
    ['Berkshire', 'Franklin District'],
    ['Berlin', 'Washington District'],
    ['Bethel', 'Windsor District'],
    ['Bloomfield', 'Essex District'],
    ['Bolton', 'Chittenden-Southeast District'],
    ['Bradford', 'Orange District'],
    ['Braintree', 'Washington District'],
    ['Brandon', 'Rutland District'],
    ['Brattleboro', 'Windham District'],
    ['Bridgewater', 'Windsor District'],
    ['Bridport', 'Addison District'],
    ['Brighton', 'Essex District'],
    ['Bristol', 'Addison District'],
    ['Brookfield', 'Orange District'],
    ['Brookline', 'Windham District'],
    ['Brownington', 'Orleans District'],
    ['Brunswick', 'Essex District'],
    ['Buel\'s Gore', 'Addison District'],
    ['Burke', 'Orleans District'],
    ['Burlington', 'Chittenden-Central District'],
    ['Burlington', 'Chittenden-Southeast District'],
    ['Cabot', 'Washington District'],
    ['Calais', 'Washington District'],
    ['Cambridge', 'Lamoille District'],
    ['Canaan', 'Essex District'],
    ['Castleton', 'Rutland District'],
    ['Cavendish', 'Windsor District'],
    ['Charleston', 'Orleans District'],
    ['Charlotte', 'Chittenden-Southeast District'],
    ['Chelsea', 'Orange District'],
    ['Chester', 'Windsor District'],
    ['Chittenden', 'Rutland District'],
    ['Clarendon', 'Rutland District'],
    ['Colchester', 'Chittenden-Central District'],
    ['Colchester', 'Grand Isle District'],
    ['Concord', 'Essex District'],
    ['Corinth', 'Orange District'],
    ['Cornwall', 'Addison District'],
    ['Coventry', 'Orleans District'],
    ['Craftsbury', 'Orleans District'],
    ['Danby', 'Rutland District'],
    ['Danville', 'Caledonia District'],
    ['Derby', 'Essex District'],
    ['Dorset', 'Bennington District'],
    ['Dover', 'Windham District'],
    ['Dummerston', 'Windham District'],
    ['Duxbury', 'Washington District'],
    ['East Haven', 'Essex District'],
    ['East Montpelier', 'Washington District'],
    ['Eden', 'Lamoille District'],
    ['Elmore', 'Lamoille District'],
    ['Enosburgh', 'Franklin District'],
    ['Essex', 'Chittenden-Central District'],
    ['Essex', 'Chittenden-North District'],
    ['Fair Haven', 'Rutland District'],
    ['Fairfax', 'Chittenden-North District'],
    ['Fairfield', 'Franklin District'],
    ['Fairlee', 'Orange District'],
    ['Fayston', 'Washington District'],
    ['Ferdinand', 'Essex District'],
    ['Ferrisburg', 'Addison District'],
    ['Ferrisburgh', 'Addison District'],
    ['Fletcher', 'Lamoille District'],
    ['Franklin', 'Franklin District'],
    ['Georgia', 'Franklin District'],
    ['Glastenbury', 'Bennington District'],
    ['Glover', 'Orleans District'],
    ['Goshen', 'Addison District'],
    ['Grafton', 'Windham District'],
    ['Granby', 'Essex District'],
    ['Grand Isle', 'Grand Isle District'],
    ['Granville', 'Addison District'],
    ['Greensboro', 'Orleans District'],
    ['Groton', 'Caledonia District'],
    ['Guildhall', 'Essex District'],
    ['Guilford', 'Windham District'],
    ['Halifax', 'Windham District'],
    ['Hancock', 'Addison District'],
    ['Hardwick', 'Caledonia District'],
    ['Hartford', 'Windsor District'],
    ['Hartland', 'Windsor District'],
    ['Highgate', 'Franklin District'],
    ['Hinesburg', 'Chittenden-Southeast District'],
    ['Holland', 'Essex District'],
    ['Hubbardton', 'Rutland District'],
    ['Huntington', 'Addison District'],
    ['Hyde Park', 'Lamoille District'],
    ['Ira', 'Rutland District'],
    ['Irasburg', 'Orleans District'],
    ['Isle La Motte', 'Grand Isle District'],
    ['Jamaica', 'Windham District'],
    ['Jay', 'Orleans District'],
    ['Jericho', 'Chittenden-Southeast District'],
    ['Johnson', 'Lamoille District'],
    ['Killington', 'Rutland District'],
    ['Kirby', 'Essex District'],
    ['Landgrove', 'Bennington District'],
    ['Leicester', 'Addison District'],
    ['Lemington', 'Essex District'],
    ['Lewis', 'Essex District'],
    ['Lincoln', 'Addison District'],
    ['Londonderry', 'Bennington District'],
    ['Lowell', 'Orleans District'],
    ['Ludlow', 'Windsor District'],
    ['Lunenburg', 'Essex District'],
    ['Lyndon', 'Essex District'],
    ['Maidstone', 'Essex District'],
    ['Manchester', 'Bennington District'],
    ['Manchester Center', 'Bennington District'],
    ['Marlboro', 'Windham District'],
    ['Marshfield', 'Washington District'],
    ['Mendon', 'Rutland District'],
    ['Middlebury', 'Addison District'],
    ['Middlesex', 'Washington District'],
    ['Middletown Springs', 'Rutland District'],
    ['Milton', 'Chittenden-North District'],
    ['Monkton', 'Addison District'],
    ['Montgomery', 'Orleans District'],
    ['Montpelier', 'Washington District'],
    ['Moretown', 'Washington District'],
    ['Morgan', 'Essex District'],
    ['Morristown', 'Lamoille District'],
    ['Mount Holly', 'Rutland District'],
    ['Mount Tabor', 'Rutland District'],
    ['New Haven', 'Addison District'],
    ['Newark', 'Orleans District'],
    ['Newbury', 'Caledonia District'],
    ['Newfane', 'Windham District'],
    ['Newport City', 'Essex District'],
    ['Newport Town', 'Orleans District'],
    ['North Bennington', 'Bennington District'],
    ['North Hero', 'Grand Isle District'],
    ['Northfield', 'Washington District'],
    ['Norton', 'Essex District'],
    ['Norwich', 'Windsor District'],
    ['Orange', 'Washington District'],
    ['Orwell', 'Addison District'],
    ['Panton', 'Addison District'],
    ['Pawlet', 'Rutland District'],
    ['Peacham', 'Caledonia District'],
    ['Peru', 'Bennington District'],
    ['Pittsfield', 'Windsor District'],
    ['Pittsford', 'Rutland District'],
    ['Plainfield', 'Washington District'],
    ['Plymouth', 'Windsor District'],
    ['Pomfret', 'Windsor District'],
    ['Poultney', 'Rutland District'],
    ['Pownal', 'Bennington District'],
    ['Proctor', 'Rutland District'],
    ['Putney', 'Windham District'],
    ['Randolph', 'Orange District'],
    ['Reading', 'Windsor District'],
    ['Readsboro', 'Bennington District'],
    ['Richford', 'Franklin District'],
    ['Richmond', 'Chittenden-Southeast District'],
    ['Ripton', 'Addison District'],
    ['Rochester', 'Addison District'],
    ['Rockingham', 'Windham District'],
    ['Roxbury', 'Washington District'],
    ['Royalton', 'Windsor District'],
    ['Rupert', 'Bennington District'],
    ['Rutland City', 'Rutland District'],
    ['Ryegate', 'Caledonia District'],
    ['Salisbury', 'Addison District'],
    ['Sandgate', 'Bennington District'],
    ['Searsburg', 'Bennington District'],
    ['Shaftsbury', 'Bennington District'],
    ['Sharon', 'Windsor District'],
    ['Sheffield', 'Orleans District'],
    ['Shelburne', 'Chittenden-Southeast District'],
    ['Sheldon', 'Franklin District'],
    ['Shoreham', 'Addison District'],
    ['Shrewsbury', 'Rutland District'],
    ['Somerset', 'Bennington District'],
    ['South Burlington', 'Chittenden-Southeast District'],
    ['South Hero', 'Grand Isle District'],
    ['Springfield', 'Windsor District'],
    ['St. Albans City', 'Franklin District'],
    ['St. Albans Town', 'Franklin District'],
    ['St. George', 'Chittenden-Southeast District'],
    ['St. Johnsbury', 'Caledonia District'],
    ['Stamford', 'Bennington District'],
    ['Stannard', 'Caledonia District'],
    ['Starksboro', 'Addison District'],
    ['Stockbridge', 'Windsor District'],
    ['Stowe', 'Washington District'],
    ['Strafford', 'Orange District'],
    ['Stratton', 'Bennington District'],
    ['Sudbury', 'Rutland District'],
    ['Sunderland', 'Bennington District'],
    ['Sutton', 'Orleans District'],
    ['Swanton', 'Franklin District'],
    ['Thetford', 'Windsor District'],
    ['Tinmouth', 'Rutland District'],
    ['Topsham', 'Orange District'],
    ['Townshend', 'Windham District'],
    ['Troy', 'Orleans District'],
    ['Tunbridge', 'Orange District'],
    ['Underhill', 'Chittenden-Southeast District'],
    ['Vergennes', 'Addison District'],
    ['Vernon', 'Windham District'],
    ['Vershire', 'Orange District'],
    ['Victory', 'Essex District'],
    ['Waitsfield', 'Washington District'],
    ['Walden', 'Caledonia District'],
    ['Wallingford', 'Rutland District'],
    ['Waltham', 'Addison District'],
    ['Wardsboro', 'Windham District'],
    ['Warner\'s Grant', 'Essex District'],
    ['Warren', 'Washington District'],
    ['Warren Gore', 'Essex District'],
    ['Washington', 'Orange District'],
    ['Waterbury', 'Washington District'],
    ['Waterford', 'Caledonia District'],
    ['Waterville', 'Lamoille District'],
    ['Weathersfield', 'Windsor District'],
    ['Wells', 'Rutland District'],
    ['West Fairlee', 'Orange District'],
    ['West Haven', 'Rutland District'],
    ['West Rutland', 'Rutland District'],
    ['West Windsor', 'Windsor District'],
    ['Westfield', 'Orleans District'],
    ['Westford', 'Chittenden-North District'],
    ['Westminster', 'Windham District'],
    ['Westmore', 'Orleans District'],
    ['Weston', 'Windsor District'],
    ['Weybridge', 'Addison District'],
    ['Wheelock', 'Caledonia District'],
    ['Whiting', 'Addison District'],
    ['Whitingham', 'Windham District'],
    ['Williamstown', 'Orange District'],
    ['Williston', 'Chittenden-Southeast District'],
    ['Wilmington', 'Bennington District'],
    ['Windham', 'Windham District'],
    ['Windsor', 'Windsor District'],
    ['Winhall', 'Bennington District'],
    ['Winooski', 'Chittenden-Central District'],
    ['Wolcott', 'Lamoille District'],
    ['Woodbury', 'Washington District'],
    ['Woodford', 'Bennington District'],
    ['Woodstock', 'Windsor District'],
    ['Worcester', 'Washington District']
];