export const Vttowns = [
    'Addison',
    'Albany',
    'Alburgh',
    'Andover',
    'Arlington',
    'Athens',
    'Averill',
    'Avery\'s Gore',
    'Bakersfield',
    'Baltimore',
    'Barnard',
    'Barnet',
    'Barre City',
    'Barre Town',
    'Barton',
    'Belvidere',
    'Bennington',
    'Benson',
    'Berkshire',
    'Berlin',
    'Bethel',
    'Bloomfield',
    'Bolton',
    'Bradford',
    'Braintree',
    'Brandon',
    'Brattleboro',
    'Bridgewater',
    'Bridport',
    'Brighton',
    'Bristol',
    'Brookfield',
    'Brookline',
    'Brownington',
    'Brunswick',
    'Buel\'s Gore',
    'Burke',
    'Burlington',
    'Burlington',
    'Cabot',
    'Calais',
    'Cambridge',
    'Canaan',
    'Castleton',
    'Cavendish',
    'Charleston',
    'Charlotte',
    'Chelsea',
    'Chester',
    'Chittenden',
    'Clarendon',
    'Colchester',
    'Colchester',
    'Concord',
    'Corinth',
    'Cornwall',
    'Coventry',
    'Craftsbury',
    'Danby',
    'Danville',
    'Derby',
    'Dorset',
    'Dover',
    'Dummerston',
    'Duxbury',
    'East Haven',
    'East Montpelier',
    'Eden',
    'Elmore',
    'Enosburgh',
    'Essex',
    'Essex',
    'Fair Haven',
    'Fairfax',
    'Fairfield',
    'Fairlee',
    'Fayston',
    'Ferdinand',
    'Ferrisburg',
    'Ferrisburgh',
    'Fletcher',
    'Franklin',
    'Georgia',
    'Glastenbury',
    'Glover',
    'Goshen',
    'Grafton',
    'Granby',
    'Grand Isle',
    'Granville',
    'Greensboro',
    'Groton',
    'Guildhall',
    'Guilford',
    'Halifax',
    'Hancock',
    'Hardwick',
    'Hartford',
    'Hartland',
    'Highgate',
    'Hinesburg',
    'Holland',
    'Hubbardton',
    'Huntington',
    'Hyde Park',
    'Ira',
    'Irasburg',
    'Isle La Motte',
    'Jamaica',
    'Jay',
    'Jericho',
    'Johnson',
    'Killington',
    'Kirby',
    'Landgrove',
    'Leicester',
    'Lemington',
    'Lewis',
    'Lincoln',
    'Londonderry',
    'Lowell',
    'Ludlow',
    'Lunenburg',
    'Lyndon',
    'Maidstone',
    'Manchester',
    'Manchester Center',
    'Marlboro',
    'Marshfield',
    'Mendon',
    'Middlebury',
    'Middlesex',
    'Middletown Springs',
    'Milton',
    'Monkton',
    'Montgomery',
    'Montpelier',
    'Moretown',
    'Morgan',
    'Morristown',
    'Mount Holly',
    'Mount Tabor',
    'New Haven',
    'Newark',
    'Newbury',
    'Newfane',
    'Newport City',
    'Newport Town',
    'North Bennington',
    'North Hero',
    'Northfield',
    'Norton',
    'Norwich',
    'Orange',
    'Orwell',
    'Panton',
    'Pawlet',
    'Peacham',
    'Peru',
    'Pittsfield',
    'Pittsford',
    'Plainfield',
    'Plymouth',
    'Pomfret',
    'Poultney',
    'Pownal',
    'Proctor',
    'Putney',
    'Randolph',
    'Reading',
    'Readsboro',
    'Richford',
    'Richmond',
    'Ripton',
    'Rochester',
    'Rockingham',
    'Roxbury',
    'Royalton',
    'Rupert',
    'Rutland City',
    'Ryegate',
    'Salisbury',
    'Sandgate',
    'Searsburg',
    'Shaftsbury',
    'Sharon',
    'Sheffield',
    'Shelburne',
    'Sheldon',
    'Shoreham',
    'Shrewsbury',
    'Somerset',
    'South Burlington',
    'South Hero',
    'Springfield',
    'St. Albans City',
    'St. Albans Town',
    'St. George',
    'St. Johnsbury',
    'Stamford',
    'Stannard',
    'Starksboro',
    'Stockbridge',
    'Stowe',
    'Strafford',
    'Stratton',
    'Sudbury',
    'Sunderland',
    'Sutton',
    'Swanton',
    'Thetford',
    'Tinmouth',
    'Topsham',
    'Townshend',
    'Troy',
    'Tunbridge',
    'Underhill',
    'Vergennes',
    'Vernon',
    'Vershire',
    'Victory',
    'Waitsfield',
    'Walden',
    'Wallingford',
    'Waltham',
    'Wardsboro',
    'Warner\'s Grant',
    'Warren',
    'Warren Gore',
    'Washington',
    'Waterbury',
    'Waterford',
    'Waterville',
    'Weathersfield',
    'Wells',
    'West Fairlee',
    'West Haven',
    'West Rutland',
    'West Windsor',
    'Westfield',
    'Westford',
    'Westminster',
    'Westmore',
    'Weston',
    'Weybridge',
    'Wheelock',
    'Whiting',
    'Whitingham',
    'Williamstown',
    'Williston',
    'Wilmington',
    'Windham',
    'Windsor',
    'Winhall',
    'Winooski',
    'Wolcott',
    'Woodbury',
    'Woodford',
    'Woodstock',
    'Worcester'
];
